version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /Mero
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /Mero/server
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /MyOb/My_Obsidian_FrontEnd-main
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /MyOb/backend
    schedule:
      interval: weekly
